# Generated by Django 2.2 on 2020-11-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='phone1',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
